import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "jinsoo's Todolist",
  description: "Generated by jinsoo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="flex justify-center content-center">
        {children}
      </body>
    </html>
  );
}
